// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesAPI.DbContexts;

#nullable disable

namespace MoviesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Fantasy",
                            ReleaseYear = 1988,
                            Title = "Mr. India"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Comedy",
                            ReleaseYear = 2005,
                            Title = "Golmaal"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Drama",
                            ReleaseYear = 2003,
                            Title = "Swades"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Thriller",
                            ReleaseYear = 2008,
                            Title = "A Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Comedy",
                            ReleaseYear = 2007,
                            Title = "Bhool Bhulaiyaa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
